server:
  port: 9090
  tomcat:
    max-connections: 200
    threads:
      min-spare: 50
      max: 200
    uri-encoding: UTF-8
    keep-alive-timeout: 6000
    connection-timeout: 1000
    accept-count: 100
    mbeanregistry:
      enabled: true
spring:
  jmx:
    enabled: true
